- group_name: start_ui
  sprites:
    - name: label_start_hint
      texture_path: texture/Label_TitleHint.png
      position: [640, 600]
      size: [256, 128]           #テクスチャ描画サイズ
      anchor_point: [0.5, 0.5]
      texture_size: [1542, 1024] #テクスチャ切り出しサイズ
- group_name: title_ui
  sprites:
    - name: title_texture
      texture_path: texture/Label_Title.png
      position: [640, 360]      
      size: [1280, 720]         #テクスチャ描画サイズ
      anchor_point: [0.5, 0.5]
      texture_size: [1280, 720] #テクスチャ切り出しサイズ