name: Extract Git Diff

on:
  push:

jobs:
  extract-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show commit information
        run: |
          echo "Before: ${{ github.event.before }}"
          echo "After : ${{ github.sha }}"

      - name: Show changed files and changed functions
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}); do

            # Visual Studio関連ファイルはスキップ
            case "$file" in
              *.vcxproj|*.filters|*.user)
                echo "Skip: $file"
                continue
                ;;
            esac

            echo ""
            echo "=================================================="
            echo "File : $file"
            echo "=================================================="

            case "$file" in
              *.cpp|*.c|*.cc|*.h|*.hpp)
                echo ""
                echo "----- Changed Function -----"
                git diff -W ${{ github.event.before }} ${{ github.sha }} -- "$file"
                ;;
              *)
                echo ""
                echo "----- Diff -----"
                git diff ${{ github.event.before }} ${{ github.sha }} -- "$file"
                ;;
            esac

            echo ""
          done
